export const FETCH_DOGS = Object.freeze({
    INITIAL: "FETCH_DOGS_INITIAL",
    SUCCESS: "FETCH_DOGS_SUCCESS",
    FAILURE: "FETCH_DOGS_FAILURE"
});

export const FETCH_BREEDS = Object.freeze({
    INITIAL: "FETCH_BREEDS_INITIAL",
    SUCCESS: "FETCH_BREEDS_SUCCESS",
    FAILURE: "FETCH_BREEDS_FAILURE"
});

export const DOGS = Object.freeze({
    SET_CURRENT_BREED: "DOGS_SET_CURRENT_BREED",
    ADD_FAVORITE: "DOGS_ADD_FAVORITE",
    REMOVE_FAVORITE: "DOGS_REMOVE_FAVORITE",
    SET_SHOW_FAVORITES: "DOGS_SET_SHOW_FAVORITES",
    APPEND_CURRENT_DOGS: "DOGS_APPEND_CURRENT_DOGS",
    REFRESH_CURRENT_DOGS: "REFRESH_CURRENT_DOGS"
});

export const APP = Object.freeze({
    SET_FIRST_SEARCH: "APP_SET_FIRST_SEARCH",
    SET_DARK_THEME: "APP_SET_DARK_THEME",
    SET_SINGLE_VIEW: "APP_SET_SINGLE_VIEW",
    SET_ERROR: "APP_SET_ERROR"
});